---
title: "Solução Lista 01"
author: |
        | Nome: Caio Stoduto Ervilha
        | E-mail: caio.stoduto@aluno.ufabc.edu.br
        | Nome: Nicolas Gomes Greco
        | E-mail: nicolas.greco@aluno.ufabc.edu.br

date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T,
                      fig.align='center',
                      cache=TRUE,
                      out.width = "60%",
                      out.heigth = "60%",
                      warning=FALSE,
                      message=FALSE)
options(width =70)
```

## Exercício 01


## Exercício 02

A Maldição da Dimensionalidade é um fenômeno observado na área de Aprendizado de Máquina, no qual o aumento do número de dimensões (ou variáveis de entrada) em um conjunto de dados ocasiona o aumento exponencial da distância entre os pontos do espaço, causando sua dispersão. Esse fenômeno é prejudicial ao aprendizado de máquina, pois pode diminuir sua performance, aumentar o tempo de treinamento, dificultar a identificação de padrões e até causar o *overfitting* — quando um modelo se ajusta excessivamente aos dados de treinamento e não generaliza bem para novos dados.

Uma abordagem comum para mitigar esse problema é a aplicação de métodos de redução de dimensionalidade, que utilizam diferentes técnicas para diminuir o número de variáveis mantendo a maior quantidade possível de informação relevante.


## Exercício 03


## Exercício 04


## Exercício 05 (Opcional)


## Exercício 06 (Opcional)


## Notas adicionais

-   Todos os códigos desta lista foram realizados em Python 3.12.2;
